spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyspringboot
    username: root
    password: 952956
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

server:
  port: 6767

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  #configuration:
  #log-impl:
  #    org.apache.ibatis.logging.stdout.StdOutImpl